---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: azurevm-it21954.ddns.net
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: azurevm-it21954.ddns.net
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
